### ISSUE TITLE
Upgrading to PHP 7 + MYSQL 5.6

### ISSUE THREAD

**Issue by rowboat85** [flurinduerst/WPDistillery#23]
Hi this is not really an issue.

But letting people know if you want to upgrade to php 7 and mysql 5.6 this is the script I use after vagrant ssh

sudo apt-get update &&
sudo add-apt-repository ppa:ondrej/php &&
sudo apt-get install php7.0 &&
sudo apt-get update &&
sudo apt-get install php7.0-mysql libapache2-mod-php7.0 &&
sudo a2dismod php5 &&
sudo a2enmod php7.0 &&
sudo apt-get update &&
sudo apt-get upgrade &&
sudo apt-get install mysql-server-5.6 &&
sudo apachectl restart

**Comment by flurinduerst** [comment]
Thanks for the info :) See https://github.com/scotch-io/scotch-box/issues/157 for the scotchbox discussion on this topic. I'm actually thinking about adding a "update to php7" option in the config (although this should be done by/in scotchbox itself), really appreciate your input!

Note: This issue is related to [scotchbox](https://github.com/scotch-io/scotch-box), not WPDistillery itself.
