### ISSUE TITLE
Error on vagrant commands

### ISSUE THREAD

**Issue by rowboat85** [flurinduerst/WPDistillery#25]
Hi there,
Having these errors this morning...everything was working fine yesterday..

"An action 'up' was attempted on the machine 'default',
but another process is already executing an action on the machine.
Vagrant locks each machine for access by only one process at a time.
Please wait until the other Vagrant process finishes modifying this
machine, then try again.

If you believe this message is in error, please check the process
listing for any "ruby" or "vagrant" processes and kill them. Then
try again."

Please help! Thanks

**Comment by flurinduerst** [comment]
Hi, you can see the state of all active machines with `vagrant global-status` or just open virtualbox. Make sure you `vagrant halt` all other running  installations and try again.

Note: This issue is related to [scotchbox](https://github.com/scotch-io/scotch-box), not WPDistillery itself. I'm happy to help, but please post your scotchbox related issues at [scotchbox/issues](https://github.com/scotch-io/scotch-box/issues)
