### ISSUE TITLE
scotch/box could not be found

### ISSUE THREAD

**Issue by mcneela86** [flurinduerst/WPDistillery#31]
I get the following error when running the default configuration of WP Distillery:

_The box 'scotch/box' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/scotch/box"]
Error:_

I am running version 1.8.7 of vagrant.

I was not sure weather to open the issue here or on the Scotch Box repo.

**Comment by flurinduerst** [comment]
I'm pretty sure this is an [ScotchBox Issue](https://github.com/scotch-io/scotch-box/issues/275) Please follow the basic ScotchBox Installation ([WPDistillery Readme Step Nr.3](https://github.com/flurinduerst/WPDistillery#setup)) and try to access ScotchBox via IP. If you're able to reach it, but can't reach it AFTER executing the setup from WPDistillery, re-open/create the issue here. Otherwise, your issue belongs to ScotchBox.
