### ISSUE TITLE
Setup fails after error

### ISSUE THREAD

**Issue by mawiswiss** [flurinduerst/WPDistillery#38]
If the setup fails because of some wrong db configuration, than fix this and try to run the script again it fails because some folder already exist.

Wrong db configuration:
`==> default: Error: Datenbank konnte nicht ausgewählt werden. Wir konnten die Verbindung zum Datenbank-Server herstellen (was bedeutet, dass Benutzername und Passwort in Ordnung sind), aber wir konnten die `distillery` Datenbank nicht auswählen.`

Retry after fixing the config:
`==> default: Error: WordPress files seem to already be present here.`

In my opinion this shouldn't fail, it should log the state and continue.

**Comment by flurinduerst** [comment]
So after a failed installation (because of non-WPDistillery-related db-stuff?) you tried to install WordPress again via WPDistillery, right? Not sure I've understand correctly.

If you want to re-install WordPress, you also want to delete the WordPress files (even if it's a db-thing as config.php contains db-related data). 

btw. on what version of WPDistillery did you encounter this?

**Comment by mawiswiss** [comment]
Yes, correct. This is a WP-CLI related issue in my opinion. Instead of installing everything from scratch it should just skip it if WP Core already exist. Just my opinion. What do you think?

I'm testing the RC.

**Comment by flurinduerst** [comment]
Think so too :) That's why I added the option to set `setup:wp: false` in the config file :)
Thanks for testing the RC 👍

**Comment by brooke-heaton** [comment]
> That's why I added the option to set setup:wp: false in the config file :)

Ah, that fixes my problem as well!
