### ISSUE TITLE
Issues with page links and assets load in fresh installation

### ISSUE THREAD

**Issue by Sergeon** [flurinduerst/WPDistillery#67]
I just created a fresh wp-distillery project by cloning the project and running `vagrant up`. I have `vagrant-hostsupdater` installed.

Then I login into `/wp-admin` with default credentials. Created a new 'dashboard' page with the wordpress UI.

After that, the page is properly listed in the `pages` tab in the wp-admin UI, when I enter the admin page of the test page i got a proper permalink `http://wpdistillery.vm/dashboard/`. 

However, any attempt to navigate to `http://wpdistillery.vm/dashboard/` or `192.168.33.10/dashboard/`, gives a **not found** from the apache webserver:

![image](https://user-images.githubusercontent.com/6699334/36369821-06a6da4e-155d-11e8-84c9-0c6f99095fc1.png)

My local machine is MacOS Sierra 10.12.6.

I really don't have almost any experience with local wordpress development, so I'm not sure this is an issue with WPDistillery. I found similar issues regarding wordpress pages not found [that point to the .htaccess file](https://stackoverflow.com/questions/5182534/wordpress-is-giving-me-404-page-not-found-for-all-pages-except-the-homepage). As said in that SO answer, I change the permalink strategy to check if the issue still remains:

## Handmade Solution

So I changed the permalink strategy to `plain` in the wordpress wp-admin page. 

Then the page works properly.

I then change again the permalink structure to 'page name', **and now the old links -such as `http://wpdistillery.vm/dashboard/` - work properly**.

So, while I don't have this permalink problem anymore, it suggest something is not good with my wpdistillery or my vagrant setup. However, **I'm just using the defaults**. My local machine is brand new and I didn't use vagrant here before nor changed the default config in any way. 

## Still problems

On top of that, I can't load any assets in the pages -nor in the main page-: this is how it displays:

![image](https://user-images.githubusercontent.com/6699334/36370326-e526d642-155e-11e8-80e1-b68d65b268fb.png)

And this is my network tab in the developer tools:

![image](https://user-images.githubusercontent.com/6699334/36370498-4b615c84-155f-11e8-88d0-c8fd23c1ccee.png)

In fact, such `dist` folder doesn't even exist under my `public/wpcontent/themes/WPSeed/`...

I guess I need to run the `gulpfile`? If so, what is the proper way to do that? Or maybe is not related at all?

**Comment by flurinduerst** [comment]
Hi 
1. That you weren't able to access the page might be, because the .htaccess file was not generated (not sure tough, will check this), when saving the "permalinks"-settings in wordpress (even without changing anything) you generate that needed .htaccess file so the page is accessable, just as you did.
2. This problem is not related to WPDistillery, but to [WPSeed](wpseed.org). It is correct that you have to run gulp, to create the `dist` folder containing all assets like images, css-files, and scripts. You have to run `npm install` to install the depencies (such as gulp, and others) and then run `gulp` to create the assets. While working on the project make sure to run the `gulp watch` tasks to automatically update the dist folder while making changes to your website locally. Please check the [WPSeed Docs](https://github.com/flurinduerst/WPSeed/blob/master/README.md). I also suggest you check out a gulp tutorial or read the [gulp Docs](https://github.com/gulpjs/gulp/blob/v3.9.1/docs/getting-started.md) or [gulp Readme](https://github.com/gulpjs/gulp/tree/v3.9.1)

**Comment by Sergeon** [comment]
Now it works fine after the `gulp` call :-), thanks!

PS: maybe the need to run `npm install` and `gulp` in the default theme should be mentioned in the docs?

**Comment by scherii** [comment]
@Sergeon [Well, actually, it is.](https://github.com/flurinduerst/WPSeed/blob/master/README.md#workflow) 😃
