### ISSUE TITLE
WPSeed theme error on clean site install

### ISSUE THREAD

**Issue by johnpitchko** [flurinduerst/WPDistillery#71]
Just did a clean install of WPDistillery, using mostly default options and including the WPSeed theme. When I access my site after doing `vagrant up` I get the following error:

```
Warning: file_get_contents(http://johnpitchko.local/wp-content/themes/WPSeed/dist/rev-manifest.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in /var/www/public/wp-content/themes/WPSeed/functions/functions-wpsetup.php on line 26
```

Can confirm that /wp-content/themes/WPSeed/dist folder does not exist.

Site appears to work fine after activating a different theme.
![wp-seed-error](https://user-images.githubusercontent.com/7190681/37207669-3bd79fa8-235b-11e8-9665-281c28932637.png)

**Comment by flurinduerst** [comment]
Hey John
This issue is related to WPSeed, not WPDistillery. The error appears because WPSeed has a cache-busting feature since v 1.2.0 that creates the cache-busted css-file withing the gulp process (this actually reads the rev-manifest.json). So running the `gulp` command (as stated in the Readme of WPSeed) will remove this message.
