### ISSUE TITLE
Install multiple themes

### ISSUE THREAD

**Issue by mikaeljorhult** [flurinduerst/WPDistillery#77]
If I want to setup a child theme I would need to install both the parent theme and my custom theme.

I've looked through the shell script and from what I see you can only install one theme during provisioning. 

How would you go about doing it?

**Comment by flurinduerst** [comment]
Hi.

To make sure WPDistillery is super fast and easy to use, we decided to keep it as clean (and minimal) as possible. Since most people only install one (developer-) theme, there are no plans to support multiple-theme installs as of now. If there are multiple people that want this option, we might consider adding it.

For now, you'll have to add the child-theme folder manually.

**Comment by flurinduerst** [comment]
If you need the option to install a second theme, you can do the following:

in `wpdistillery/config.yml`:
line 70/72, add:
```
childthemes:
  url: "https://github.com/youruser/yourtheme/archive/master.zip"
``` 

in `wpdistillery/wpdistillery.sh`:
line 126, add: `wp theme install $CONF_childthemes_url --force`

untested! but that should do the trick.

**Comment by mikaeljorhult** [comment]
I fully understand wanting to keep it as simple as possible.

Will try the option out and see what I can do. Thanks!

**Comment by flurinduerst** [comment]
No problem. Feel free to let me know if that approach doesn't work. Happy to help.
