### ISSUE TITLE
wpdistillery.vm can't be reached

### ISSUE THREAD

**Issue by smth** [flurinduerst/WPDistillery#83]
I just tried creating a site, using the default settings. The site is available at http://192.168.33.10 (though all links are broken), but not at http://wpdistillery.vm

Chrome's error:
```
wpdistillery.vm’s server IP address could not be found.
ERR_NAME_NOT_RESOLVED
```

**Comment by flurinduerst** [comment]
Hi.

1. did you install Vagrant-Hostupdater using `vagrant plugin install vagrant-hostsupdater` before running the setup? 
2. What's in your hosts-file?

**Comment by smth** [comment]
Ah, no I didn't. I missed that. I guess that'd be the problem.

**Comment by flurinduerst** [comment]
That should do the trick :) If not, let me know. Happy to help!

**Comment by joshtrup1** [comment]
ive been at this for a couple hours with no luck, at first it wouldnt let me run vagrant up so i removed the hostsupdater and then it worked. Then I came to an issue where i could ping everything asked in the lab tutorial but I cant connect to the http://wpdistillery.vm page on host or kali machine. I tried a couple other things I found online no luck. Deleted everything and restarted. came back to the same exact issue.

**Comment by joshtrup1** [comment]
the second time i was actually able to run the vagrant up command with the hosts updater installed successfully which i thought was a good step in the right direction. when i pinged it also came back with the same ip address as on the tutorial (which last time it came back with a totally different one even tho I hadnt changed anything), so that was good as well. Yet im still running into the same issue.
